name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEPS_APT: curl gcc clang libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev libpipewire-0.3-dev libpango1.0-dev libdisplay-info-dev
  DEPS_DNF: cargo gcc clang libudev-devel libgbm-devel libxkbcommon-devel wayland-devel libinput-devel dbus-devel systemd-devel libseat-devel pipewire-devel pango-devel cairo-gobject-devel libdisplay-info-devel

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.DEPS_APT }} libadwaita-1-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all -- --nocapture

  build:
    name: check feature combinations
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.DEPS_APT }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --no-default-features
      - run: cargo check --no-default-features --features dbus
      - run: cargo check --no-default-features --features systemd
      - run: cargo check --no-default-features --features dinit
      - run: cargo check --no-default-features --features xdp-gnome-screencast
      - run: cargo check
      - run: cargo build --features profile-with-tracy

  randomized-tests:
    name: randomized and slow tests
    runs-on: ubuntu-24.04
    env:
      RUST_BACKTRACE: 1
      RUN_SLOW_TESTS: 1
      PROPTEST_CASES: 200000
      PROPTEST_MAX_LOCAL_REJECTS: 200000
      PROPTEST_MAX_GLOBAL_REJECTS: 200000
      PROPTEST_MAX_SHRINK_ITERS: 200000
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.DEPS_APT }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --no-run --all --exclude swayward-visual-tests --release
      - run: cargo test --all --exclude swayward-visual-tests --release

  visual-tests:
    name: visual tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.DEPS_APT }} libadwaita-1-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --package swayward-visual-tests

  msrv:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.DEPS_APT }} libadwaita-1-dev
      - uses: dtolnay/rust-toolchain@1.87.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --all-targets

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ env.DEPS_APT }} libadwaita-1-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all --all-targets

  rustfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  fedora:
    runs-on: ubuntu-24.04
    container: fedora:42
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false
      - name: Install dependencies
        run: |
          sudo dnf update -y
          sudo dnf install -y ${{ env.DEPS_DNF }} libadwaita-devel
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --all
